$(window).on('load',function(){
    $('.ico06 .btn').on('mousedown',function(){
        $(this).addClass('clck');
    }).on('mouseup',function(){
        $(this).removeClass('clck');
    });
    $('.ico07').on('mousedown',function(){
        $(this).addClass('clck');
    }).on('mouseup',function(){
        $(this).removeClass('clck');
    });
    $('.ico08').bind('click',function(){
        $(this).addClass('clck');
        setTimeout(function(){
            $(this).removeClass('clck');
        }.bind($(this)),700)
    });
    $('.ico09').bind('click',function(){
        $(this).addClass('clck');
        setTimeout(function(){
            $(this).removeClass('clck');
        }.bind($(this)),1700)
    });
    $('.ico10').bind('click',function(){
        $(this).addClass('clck');
        setTimeout(function(){
            $(this).removeClass('clck');
        }.bind($(this)),700)
    });
});